locator_type = " using locatorType "
found_locator = " Element found with locator "
not_found_locator = " Element not found with locator "
from_locator = " from element with locator value "
in_locator = " in element with locator value "
